/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegosockets.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Skhan
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form cliente
     */
    public Cliente() {
        initComponents();
        pnlCrearUnirse.setVisible(false);
        pnlTablero.setVisible(false);
        pnlUnirse.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTablero = new javax.swing.JPanel();
        pnlJugador = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lIPContra = new javax.swing.JLabel();
        lTurno = new javax.swing.JLabel();
        lDado1 = new javax.swing.JLabel();
        lDado2 = new javax.swing.JLabel();
        btLanzar = new javax.swing.JButton();
        lIPContra1 = new javax.swing.JLabel();
        lVidas = new javax.swing.JLabel();
        lNumTablero = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        bt11 = new javax.swing.JButton();
        bt12 = new javax.swing.JButton();
        bt13 = new javax.swing.JButton();
        bt14 = new javax.swing.JButton();
        bt15 = new javax.swing.JButton();
        bt16 = new javax.swing.JButton();
        bt17 = new javax.swing.JButton();
        bt18 = new javax.swing.JButton();
        bt21 = new javax.swing.JButton();
        bt22 = new javax.swing.JButton();
        bt23 = new javax.swing.JButton();
        bt24 = new javax.swing.JButton();
        bt25 = new javax.swing.JButton();
        bt26 = new javax.swing.JButton();
        bt27 = new javax.swing.JButton();
        bt28 = new javax.swing.JButton();
        bt31 = new javax.swing.JButton();
        bt32 = new javax.swing.JButton();
        bt33 = new javax.swing.JButton();
        bt34 = new javax.swing.JButton();
        bt35 = new javax.swing.JButton();
        bt36 = new javax.swing.JButton();
        bt37 = new javax.swing.JButton();
        bt38 = new javax.swing.JButton();
        bt41 = new javax.swing.JButton();
        bt42 = new javax.swing.JButton();
        bt43 = new javax.swing.JButton();
        bt44 = new javax.swing.JButton();
        bt45 = new javax.swing.JButton();
        bt46 = new javax.swing.JButton();
        bt47 = new javax.swing.JButton();
        bt48 = new javax.swing.JButton();
        bt51 = new javax.swing.JButton();
        bt52 = new javax.swing.JButton();
        bt53 = new javax.swing.JButton();
        bt54 = new javax.swing.JButton();
        bt55 = new javax.swing.JButton();
        bt56 = new javax.swing.JButton();
        bt57 = new javax.swing.JButton();
        bt58 = new javax.swing.JButton();
        bt63 = new javax.swing.JButton();
        bt68 = new javax.swing.JButton();
        bt67 = new javax.swing.JButton();
        bt66 = new javax.swing.JButton();
        bt65 = new javax.swing.JButton();
        bt64 = new javax.swing.JButton();
        bt62 = new javax.swing.JButton();
        bt61 = new javax.swing.JButton();
        bt77 = new javax.swing.JButton();
        bt78 = new javax.swing.JButton();
        bt73 = new javax.swing.JButton();
        bt74 = new javax.swing.JButton();
        bt75 = new javax.swing.JButton();
        bt71 = new javax.swing.JButton();
        bt72 = new javax.swing.JButton();
        bt76 = new javax.swing.JButton();
        bt86 = new javax.swing.JButton();
        bt82 = new javax.swing.JButton();
        bt81 = new javax.swing.JButton();
        bt85 = new javax.swing.JButton();
        bt84 = new javax.swing.JButton();
        bt83 = new javax.swing.JButton();
        bt88 = new javax.swing.JButton();
        bt87 = new javax.swing.JButton();
        lInstruccion = new javax.swing.JLabel();
        pnlCrearUnirse = new javax.swing.JPanel();
        lConectado = new javax.swing.JLabel();
        btCrear = new javax.swing.JButton();
        btUnirse = new javax.swing.JButton();
        pnlUnirse = new javax.swing.JPanel();
        btUnirsePartida = new javax.swing.JButton();
        idPartida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnlIServer = new javax.swing.JPanel();
        btConectarServidor = new javax.swing.JButton();
        IPServidor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel3.setText("Jugando contra:");

        lIPContra.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        lIPContra.setForeground(new java.awt.Color(0, 153, 51));
        lIPContra.setText("Vidas: ");

        lTurno.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        lTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTurno.setText("...");

        lDado1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lDado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDado1.setText("6");

        lDado2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lDado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDado2.setText("6");

        btLanzar.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        btLanzar.setForeground(new java.awt.Color(0, 51, 255));
        btLanzar.setText("Lanzar");
        btLanzar.setBorderPainted(false);
        btLanzar.setEnabled(false);

        lIPContra1.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        lIPContra1.setForeground(new java.awt.Color(255, 0, 0));
        lIPContra1.setText("Esperando...");

        lVidas.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        lVidas.setForeground(new java.awt.Color(0, 153, 51));

        lNumTablero.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        lNumTablero.setText("Tablero #");

        javax.swing.GroupLayout pnlJugadorLayout = new javax.swing.GroupLayout(pnlJugador);
        pnlJugador.setLayout(pnlJugadorLayout);
        pnlJugadorLayout.setHorizontalGroup(
            pnlJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addGroup(pnlJugadorLayout.createSequentialGroup()
                        .addGroup(pnlJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlJugadorLayout.createSequentialGroup()
                                .addComponent(lIPContra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lVidas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lTurno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJugadorLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(btLanzar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(pnlJugadorLayout.createSequentialGroup()
                        .addComponent(lNumTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pnlJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlJugadorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lIPContra1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlJugadorLayout.setVerticalGroup(
            pnlJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugadorLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lIPContra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lVidas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDado2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDado1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(lNumTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
            .addGroup(pnlJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlJugadorLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(lIPContra1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(326, Short.MAX_VALUE)))
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("1");
        jLabel5.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("2");
        jLabel6.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel6.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("3");
        jLabel7.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel7.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel7.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("4");
        jLabel8.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel8.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel8.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("5");
        jLabel9.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel9.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel9.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("6");
        jLabel10.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel10.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel10.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("7");
        jLabel11.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel11.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel11.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("8");
        jLabel12.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel12.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel12.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("1");
        jLabel13.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel13.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel13.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("2");
        jLabel14.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel14.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel14.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("3");
        jLabel15.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel15.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel15.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("4");
        jLabel16.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel16.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel16.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("5");
        jLabel17.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel17.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel17.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("6");
        jLabel18.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel18.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel18.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("7");
        jLabel19.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel19.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel19.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("8");
        jLabel20.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel20.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel20.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[1][1] = bt11;
        bt11.setBackground(new java.awt.Color(255, 255, 255));
        bt11.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt11.setMaximumSize(new java.awt.Dimension(25, 25));
        bt11.setMinimumSize(new java.awt.Dimension(25, 25));
        bt11.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[1][2] = bt12;
        bt12.setBackground(new java.awt.Color(255, 255, 255));
        bt12.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt12.setMaximumSize(new java.awt.Dimension(25, 25));
        bt12.setMinimumSize(new java.awt.Dimension(25, 25));
        bt12.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[1][3] = bt13;
        bt13.setBackground(new java.awt.Color(255, 255, 255));
        bt13.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt13.setMaximumSize(new java.awt.Dimension(25, 25));
        bt13.setMinimumSize(new java.awt.Dimension(25, 25));
        bt13.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[1][4] = bt14;
        bt14.setBackground(new java.awt.Color(255, 255, 255));
        bt14.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt14.setMaximumSize(new java.awt.Dimension(25, 25));
        bt14.setMinimumSize(new java.awt.Dimension(25, 25));
        bt14.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[1][5] = bt15;
        bt15.setBackground(new java.awt.Color(255, 255, 255));
        bt15.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt15.setMaximumSize(new java.awt.Dimension(25, 25));
        bt15.setMinimumSize(new java.awt.Dimension(25, 25));
        bt15.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[1][6] = bt16;
        bt16.setBackground(new java.awt.Color(255, 255, 255));
        bt16.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt16.setMaximumSize(new java.awt.Dimension(25, 25));
        bt16.setMinimumSize(new java.awt.Dimension(25, 25));
        bt16.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[1][7] = bt17;
        bt17.setBackground(new java.awt.Color(255, 255, 255));
        bt17.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt17.setMaximumSize(new java.awt.Dimension(25, 25));
        bt17.setMinimumSize(new java.awt.Dimension(25, 25));
        bt17.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[1][8] = bt18;
        bt18.setBackground(new java.awt.Color(255, 255, 255));
        bt18.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt18.setMaximumSize(new java.awt.Dimension(25, 25));
        bt18.setMinimumSize(new java.awt.Dimension(25, 25));
        bt18.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[2][1] = bt21;
        bt21.setBackground(new java.awt.Color(255, 255, 255));
        bt21.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt21.setMaximumSize(new java.awt.Dimension(25, 25));
        bt21.setMinimumSize(new java.awt.Dimension(25, 25));
        bt21.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[2][2] = bt22;
        bt22.setBackground(new java.awt.Color(255, 255, 255));
        bt22.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt22.setMaximumSize(new java.awt.Dimension(25, 25));
        bt22.setMinimumSize(new java.awt.Dimension(25, 25));
        bt22.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[2][3] = bt23;
        bt23.setBackground(new java.awt.Color(255, 255, 255));
        bt23.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt23.setMaximumSize(new java.awt.Dimension(25, 25));
        bt23.setMinimumSize(new java.awt.Dimension(25, 25));
        bt23.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[2][4] = bt24;
        bt24.setBackground(new java.awt.Color(255, 255, 255));
        bt24.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt24.setMaximumSize(new java.awt.Dimension(25, 25));
        bt24.setMinimumSize(new java.awt.Dimension(25, 25));
        bt24.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[2][5] = bt25;
        bt25.setBackground(new java.awt.Color(255, 255, 255));
        bt25.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt25.setMaximumSize(new java.awt.Dimension(25, 25));
        bt25.setMinimumSize(new java.awt.Dimension(25, 25));
        bt25.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[2][6] = bt26;
        bt26.setBackground(new java.awt.Color(255, 255, 255));
        bt26.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt26.setMaximumSize(new java.awt.Dimension(25, 25));
        bt26.setMinimumSize(new java.awt.Dimension(25, 25));
        bt26.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[2][7] = bt27;
        bt27.setBackground(new java.awt.Color(255, 255, 255));
        bt27.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt27.setMaximumSize(new java.awt.Dimension(25, 25));
        bt27.setMinimumSize(new java.awt.Dimension(25, 25));
        bt27.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[2][8] = bt28;
        bt28.setBackground(new java.awt.Color(255, 255, 255));
        bt28.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt28.setMaximumSize(new java.awt.Dimension(25, 25));
        bt28.setMinimumSize(new java.awt.Dimension(25, 25));
        bt28.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[3][1] = bt31;
        bt31.setBackground(new java.awt.Color(255, 255, 255));
        bt31.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt31.setMaximumSize(new java.awt.Dimension(25, 25));
        bt31.setMinimumSize(new java.awt.Dimension(25, 25));
        bt31.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[3][2] = bt32;
        bt32.setBackground(new java.awt.Color(255, 255, 255));
        bt32.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt32.setMaximumSize(new java.awt.Dimension(25, 25));
        bt32.setMinimumSize(new java.awt.Dimension(25, 25));
        bt32.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[3][3] = bt33;
        bt33.setBackground(new java.awt.Color(255, 255, 255));
        bt33.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt33.setMaximumSize(new java.awt.Dimension(25, 25));
        bt33.setMinimumSize(new java.awt.Dimension(25, 25));
        bt33.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[3][4] = bt34;
        bt34.setBackground(new java.awt.Color(255, 255, 255));
        bt34.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt34.setMaximumSize(new java.awt.Dimension(25, 25));
        bt34.setMinimumSize(new java.awt.Dimension(25, 25));
        bt34.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[3][5] = bt35;
        bt35.setBackground(new java.awt.Color(255, 255, 255));
        bt35.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt35.setMaximumSize(new java.awt.Dimension(25, 25));
        bt35.setMinimumSize(new java.awt.Dimension(25, 25));
        bt35.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[3][6] = bt36;
        bt36.setBackground(new java.awt.Color(255, 255, 255));
        bt36.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt36.setMaximumSize(new java.awt.Dimension(25, 25));
        bt36.setMinimumSize(new java.awt.Dimension(25, 25));
        bt36.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[3][7] = bt37;
        bt37.setBackground(new java.awt.Color(255, 255, 255));
        bt37.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt37.setMaximumSize(new java.awt.Dimension(25, 25));
        bt37.setMinimumSize(new java.awt.Dimension(25, 25));
        bt37.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[3][8] = bt38;
        bt38.setBackground(new java.awt.Color(255, 255, 255));
        bt38.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt38.setMaximumSize(new java.awt.Dimension(25, 25));
        bt38.setMinimumSize(new java.awt.Dimension(25, 25));
        bt38.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[4][1] = bt41;
        bt41.setBackground(new java.awt.Color(255, 255, 255));
        bt41.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt41.setMaximumSize(new java.awt.Dimension(25, 25));
        bt41.setMinimumSize(new java.awt.Dimension(25, 25));
        bt41.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[4][2] = bt42;
        bt42.setBackground(new java.awt.Color(255, 255, 255));
        bt42.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt42.setMaximumSize(new java.awt.Dimension(25, 25));
        bt42.setMinimumSize(new java.awt.Dimension(25, 25));
        bt42.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[4][3] = bt43;
        bt43.setBackground(new java.awt.Color(255, 255, 255));
        bt43.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt43.setMaximumSize(new java.awt.Dimension(25, 25));
        bt43.setMinimumSize(new java.awt.Dimension(25, 25));
        bt43.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[4][4] = bt44;
        bt44.setBackground(new java.awt.Color(255, 255, 255));
        bt44.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt44.setMaximumSize(new java.awt.Dimension(25, 25));
        bt44.setMinimumSize(new java.awt.Dimension(25, 25));
        bt44.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[4][5] = bt45;
        bt45.setBackground(new java.awt.Color(255, 255, 255));
        bt45.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt45.setMaximumSize(new java.awt.Dimension(25, 25));
        bt45.setMinimumSize(new java.awt.Dimension(25, 25));
        bt45.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[4][6] = bt46;
        bt46.setBackground(new java.awt.Color(255, 255, 255));
        bt46.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt46.setMaximumSize(new java.awt.Dimension(25, 25));
        bt46.setMinimumSize(new java.awt.Dimension(25, 25));
        bt46.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[4][7] = bt47;
        bt47.setBackground(new java.awt.Color(255, 255, 255));
        bt47.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt47.setMaximumSize(new java.awt.Dimension(25, 25));
        bt47.setMinimumSize(new java.awt.Dimension(25, 25));
        bt47.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[4][8] = bt48;
        bt48.setBackground(new java.awt.Color(255, 255, 255));
        bt48.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt48.setMaximumSize(new java.awt.Dimension(25, 25));
        bt48.setMinimumSize(new java.awt.Dimension(25, 25));
        bt48.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[5][1] = bt51;
        bt51.setBackground(new java.awt.Color(255, 255, 255));
        bt51.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt51.setMaximumSize(new java.awt.Dimension(25, 25));
        bt51.setMinimumSize(new java.awt.Dimension(25, 25));
        bt51.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[5][2] = bt52;
        bt52.setBackground(new java.awt.Color(255, 255, 255));
        bt52.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt52.setMaximumSize(new java.awt.Dimension(25, 25));
        bt52.setMinimumSize(new java.awt.Dimension(25, 25));
        bt52.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[5][3] = bt53;
        bt53.setBackground(new java.awt.Color(255, 255, 255));
        bt53.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt53.setMaximumSize(new java.awt.Dimension(25, 25));
        bt53.setMinimumSize(new java.awt.Dimension(25, 25));
        bt53.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[5][4] = bt54;
        bt54.setBackground(new java.awt.Color(255, 255, 255));
        bt54.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt54.setMaximumSize(new java.awt.Dimension(25, 25));
        bt54.setMinimumSize(new java.awt.Dimension(25, 25));
        bt54.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[5][5] = bt55;
        bt55.setBackground(new java.awt.Color(255, 255, 255));
        bt55.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt55.setMaximumSize(new java.awt.Dimension(25, 25));
        bt55.setMinimumSize(new java.awt.Dimension(25, 25));
        bt55.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[5][6] = bt56;
        bt56.setBackground(new java.awt.Color(255, 255, 255));
        bt56.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt56.setMaximumSize(new java.awt.Dimension(25, 25));
        bt56.setMinimumSize(new java.awt.Dimension(25, 25));
        bt56.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[5][7] = bt57;
        bt57.setBackground(new java.awt.Color(255, 255, 255));
        bt57.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt57.setMaximumSize(new java.awt.Dimension(25, 25));
        bt57.setMinimumSize(new java.awt.Dimension(25, 25));
        bt57.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[5][8] = bt58;
        bt58.setBackground(new java.awt.Color(255, 255, 255));
        bt58.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt58.setMaximumSize(new java.awt.Dimension(25, 25));
        bt58.setMinimumSize(new java.awt.Dimension(25, 25));
        bt58.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[6][3] = bt63;
        bt63.setBackground(new java.awt.Color(255, 255, 255));
        bt63.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt63.setMaximumSize(new java.awt.Dimension(25, 25));
        bt63.setMinimumSize(new java.awt.Dimension(25, 25));
        bt63.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[6][8] = bt68;
        bt68.setBackground(new java.awt.Color(255, 255, 255));
        bt68.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt68.setMaximumSize(new java.awt.Dimension(25, 25));
        bt68.setMinimumSize(new java.awt.Dimension(25, 25));
        bt68.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[6][7] = bt67;
        bt67.setBackground(new java.awt.Color(255, 255, 255));
        bt67.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt67.setMaximumSize(new java.awt.Dimension(25, 25));
        bt67.setMinimumSize(new java.awt.Dimension(25, 25));
        bt67.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[6][6] = bt66;
        bt66.setBackground(new java.awt.Color(255, 255, 255));
        bt66.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt66.setMaximumSize(new java.awt.Dimension(25, 25));
        bt66.setMinimumSize(new java.awt.Dimension(25, 25));
        bt66.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[6][5] = bt65;
        bt65.setBackground(new java.awt.Color(255, 255, 255));
        bt65.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt65.setMaximumSize(new java.awt.Dimension(25, 25));
        bt65.setMinimumSize(new java.awt.Dimension(25, 25));
        bt65.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[6][4] = bt64;
        bt64.setBackground(new java.awt.Color(255, 255, 255));
        bt64.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt64.setMaximumSize(new java.awt.Dimension(25, 25));
        bt64.setMinimumSize(new java.awt.Dimension(25, 25));
        bt64.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[6][2] = bt62;
        bt62.setBackground(new java.awt.Color(255, 255, 255));
        bt62.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt62.setMaximumSize(new java.awt.Dimension(25, 25));
        bt62.setMinimumSize(new java.awt.Dimension(25, 25));
        bt62.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[6][1] = bt61;
        bt61.setBackground(new java.awt.Color(255, 255, 255));
        bt61.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt61.setMaximumSize(new java.awt.Dimension(25, 25));
        bt61.setMinimumSize(new java.awt.Dimension(25, 25));
        bt61.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[7][7] = bt77;
        bt77.setBackground(new java.awt.Color(255, 255, 255));
        bt77.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt77.setMaximumSize(new java.awt.Dimension(25, 25));
        bt77.setMinimumSize(new java.awt.Dimension(25, 25));
        bt77.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[7][8] = bt78;
        bt78.setBackground(new java.awt.Color(255, 255, 255));
        bt78.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt78.setMaximumSize(new java.awt.Dimension(25, 25));
        bt78.setMinimumSize(new java.awt.Dimension(25, 25));
        bt78.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[7][3] = bt73;
        bt73.setBackground(new java.awt.Color(255, 255, 255));
        bt73.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt73.setMaximumSize(new java.awt.Dimension(25, 25));
        bt73.setMinimumSize(new java.awt.Dimension(25, 25));
        bt73.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[7][4] = bt74;
        bt74.setBackground(new java.awt.Color(255, 255, 255));
        bt74.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt74.setMaximumSize(new java.awt.Dimension(25, 25));
        bt74.setMinimumSize(new java.awt.Dimension(25, 25));
        bt74.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[7][5] = bt75;
        bt75.setBackground(new java.awt.Color(255, 255, 255));
        bt75.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt75.setMaximumSize(new java.awt.Dimension(25, 25));
        bt75.setMinimumSize(new java.awt.Dimension(25, 25));
        bt75.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[7][1] = bt71;
        bt71.setBackground(new java.awt.Color(255, 255, 255));
        bt71.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt71.setMaximumSize(new java.awt.Dimension(25, 25));
        bt71.setMinimumSize(new java.awt.Dimension(25, 25));
        bt71.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[7][2] = bt72;
        bt72.setBackground(new java.awt.Color(255, 255, 255));
        bt72.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt72.setMaximumSize(new java.awt.Dimension(25, 25));
        bt72.setMinimumSize(new java.awt.Dimension(25, 25));
        bt72.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[7][6] = bt76;
        bt76.setBackground(new java.awt.Color(255, 255, 255));
        bt76.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt76.setMaximumSize(new java.awt.Dimension(25, 25));
        bt76.setMinimumSize(new java.awt.Dimension(25, 25));
        bt76.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[8][6] = bt86;
        bt86.setBackground(new java.awt.Color(255, 255, 255));
        bt86.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt86.setMaximumSize(new java.awt.Dimension(25, 25));
        bt86.setMinimumSize(new java.awt.Dimension(25, 25));
        bt86.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[8][2] = bt82;
        bt82.setBackground(new java.awt.Color(255, 255, 255));
        bt82.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt82.setMaximumSize(new java.awt.Dimension(25, 25));
        bt82.setMinimumSize(new java.awt.Dimension(25, 25));
        bt82.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[8][1] = bt81;
        bt81.setBackground(new java.awt.Color(255, 255, 255));
        bt81.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt81.setMaximumSize(new java.awt.Dimension(25, 25));
        bt81.setMinimumSize(new java.awt.Dimension(25, 25));
        bt81.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[8][5] = bt85;
        bt85.setBackground(new java.awt.Color(255, 255, 255));
        bt85.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt85.setMaximumSize(new java.awt.Dimension(25, 25));
        bt85.setMinimumSize(new java.awt.Dimension(25, 25));
        bt85.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[8][4] = bt84;
        bt84.setBackground(new java.awt.Color(255, 255, 255));
        bt84.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt84.setMaximumSize(new java.awt.Dimension(25, 25));
        bt84.setMinimumSize(new java.awt.Dimension(25, 25));
        bt84.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[8][3] = bt83;
        bt83.setBackground(new java.awt.Color(255, 255, 255));
        bt83.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt83.setMaximumSize(new java.awt.Dimension(25, 25));
        bt83.setMinimumSize(new java.awt.Dimension(25, 25));
        bt83.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[8][8] = bt88;
        bt88.setBackground(new java.awt.Color(255, 255, 255));
        bt88.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt88.setMaximumSize(new java.awt.Dimension(25, 25));
        bt88.setMinimumSize(new java.awt.Dimension(25, 25));
        bt88.setPreferredSize(new java.awt.Dimension(25, 25));

        posicion[8][7] = bt87;
        bt87.setBackground(new java.awt.Color(255, 255, 255));
        bt87.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        bt87.setMaximumSize(new java.awt.Dimension(25, 25));
        bt87.setMinimumSize(new java.awt.Dimension(25, 25));
        bt87.setPreferredSize(new java.awt.Dimension(25, 25));

        lInstruccion.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlTableroLayout = new javax.swing.GroupLayout(pnlTablero);
        pnlTablero.setLayout(pnlTableroLayout);
        pnlTableroLayout.setHorizontalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTableroLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTableroLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlTableroLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTableroLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bt12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTableroLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableroLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(bt15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTableroLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTableroLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(bt17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTableroLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bt18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTableroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(bt24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bt28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTableroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(bt34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bt38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTableroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(bt44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bt48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTableroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(bt54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt55, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt56, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bt58, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTableroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt61, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt62, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt63, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(bt64, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt65, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt66, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt67, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bt68, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTableroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt71, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt72, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt73, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(bt74, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt75, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt76, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt77, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bt78, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTableroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt81, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt82, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt83, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(bt84, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt85, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt86, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(bt87, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bt88, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(pnlJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        pnlTableroLayout.setVerticalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTableroLayout.createSequentialGroup()
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTableroLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTableroLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlTableroLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(bt11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTableroLayout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(bt12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTableroLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(bt13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTableroLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(bt14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTableroLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(bt15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTableroLayout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(bt16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTableroLayout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(bt17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTableroLayout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(bt18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt55, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt56, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt58, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt61, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt62, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt63, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt64, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt65, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt66, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt67, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt68, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt71, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt72, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt73, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt74, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt75, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt76, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt77, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt78, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt81, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt82, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt83, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt84, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt85, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt86, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt87, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt88, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnlJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lConectado.setForeground(new java.awt.Color(0, 204, 0));
        lConectado.setText("Conectado");

        btCrear.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btCrear.setText("Crear");

        btUnirse.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        btUnirse.setText("Unirse");

        javax.swing.GroupLayout pnlCrearUnirseLayout = new javax.swing.GroupLayout(pnlCrearUnirse);
        pnlCrearUnirse.setLayout(pnlCrearUnirseLayout);
        pnlCrearUnirseLayout.setHorizontalGroup(
            pnlCrearUnirseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearUnirseLayout.createSequentialGroup()
                .addComponent(lConectado)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlCrearUnirseLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(pnlCrearUnirseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btUnirse, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );
        pnlCrearUnirseLayout.setVerticalGroup(
            pnlCrearUnirseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCrearUnirseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btUnirse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lConectado))
        );

        btUnirsePartida.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        btUnirsePartida.setText("Unirse");

        idPartida.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        idPartida.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel4.setText("Unirse");

        jLabel21.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel21.setText("Ingrese la ID de la partida:");

        javax.swing.GroupLayout pnlUnirseLayout = new javax.swing.GroupLayout(pnlUnirse);
        pnlUnirse.setLayout(pnlUnirseLayout);
        pnlUnirseLayout.setHorizontalGroup(
            pnlUnirseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnirseLayout.createSequentialGroup()
                .addGroup(pnlUnirseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUnirseLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(idPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUnirseLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel21))
                    .addGroup(pnlUnirseLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btUnirsePartida))
                    .addGroup(pnlUnirseLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel4)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnlUnirseLayout.setVerticalGroup(
            pnlUnirseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUnirseLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btUnirsePartida)
                .addContainerGap())
        );

        pnlIServer.setMinimumSize(new java.awt.Dimension(226, 130));
        pnlIServer.setPreferredSize(new java.awt.Dimension(226, 130));

        btConectarServidor.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        btConectarServidor.setText("Conectar");

        IPServidor.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        IPServidor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IPServidor.setText("192.168.1.");

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel1.setText("Cliente");

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese la IP del servidor:");

        javax.swing.GroupLayout pnlIServerLayout = new javax.swing.GroupLayout(pnlIServer);
        pnlIServer.setLayout(pnlIServerLayout);
        pnlIServerLayout.setHorizontalGroup(
            pnlIServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIServerLayout.createSequentialGroup()
                .addGroup(pnlIServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIServerLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(IPServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlIServerLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2))
                    .addGroup(pnlIServerLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(pnlIServerLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btConectarServidor)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pnlIServerLayout.setVerticalGroup(
            pnlIServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIServerLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IPServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConectarServidor)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIServer, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlCrearUnirse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 55, Short.MAX_VALUE)
                    .addComponent(pnlTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 55, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addComponent(pnlUnirse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(226, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIServer, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlCrearUnirse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(178, 178, 178)
                    .addComponent(pnlUnirse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void noConectado(){
        JOptionPane.showMessageDialog(null, "Partida no encontrada", "ERROR de conexion", JOptionPane.WARNING_MESSAGE);
    }
    
    public void noPuede(){
        JOptionPane.showMessageDialog(null, "No tienes tantos movimientos", "Acción no permitida", JOptionPane.WARNING_MESSAGE);
    }
    
    public void AnunciaGanador(String ganador, String mensaje){
        JOptionPane.showMessageDialog(null, mensaje, ganador, JOptionPane.WARNING_MESSAGE);
    }
    
    
    public javax.swing.JButton[][] posicion = new javax.swing.JButton[9][9];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField IPServidor;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt13;
    private javax.swing.JButton bt14;
    private javax.swing.JButton bt15;
    private javax.swing.JButton bt16;
    private javax.swing.JButton bt17;
    private javax.swing.JButton bt18;
    private javax.swing.JButton bt21;
    private javax.swing.JButton bt22;
    private javax.swing.JButton bt23;
    private javax.swing.JButton bt24;
    private javax.swing.JButton bt25;
    private javax.swing.JButton bt26;
    private javax.swing.JButton bt27;
    private javax.swing.JButton bt28;
    private javax.swing.JButton bt31;
    private javax.swing.JButton bt32;
    private javax.swing.JButton bt33;
    private javax.swing.JButton bt34;
    private javax.swing.JButton bt35;
    private javax.swing.JButton bt36;
    private javax.swing.JButton bt37;
    private javax.swing.JButton bt38;
    private javax.swing.JButton bt41;
    private javax.swing.JButton bt42;
    private javax.swing.JButton bt43;
    private javax.swing.JButton bt44;
    private javax.swing.JButton bt45;
    private javax.swing.JButton bt46;
    private javax.swing.JButton bt47;
    private javax.swing.JButton bt48;
    private javax.swing.JButton bt51;
    private javax.swing.JButton bt52;
    private javax.swing.JButton bt53;
    private javax.swing.JButton bt54;
    private javax.swing.JButton bt55;
    private javax.swing.JButton bt56;
    private javax.swing.JButton bt57;
    private javax.swing.JButton bt58;
    private javax.swing.JButton bt61;
    private javax.swing.JButton bt62;
    private javax.swing.JButton bt63;
    private javax.swing.JButton bt64;
    private javax.swing.JButton bt65;
    private javax.swing.JButton bt66;
    private javax.swing.JButton bt67;
    private javax.swing.JButton bt68;
    private javax.swing.JButton bt71;
    private javax.swing.JButton bt72;
    private javax.swing.JButton bt73;
    private javax.swing.JButton bt74;
    private javax.swing.JButton bt75;
    private javax.swing.JButton bt76;
    private javax.swing.JButton bt77;
    private javax.swing.JButton bt78;
    private javax.swing.JButton bt81;
    private javax.swing.JButton bt82;
    private javax.swing.JButton bt83;
    private javax.swing.JButton bt84;
    private javax.swing.JButton bt85;
    private javax.swing.JButton bt86;
    private javax.swing.JButton bt87;
    private javax.swing.JButton bt88;
    public javax.swing.JButton btConectarServidor;
    public javax.swing.JButton btCrear;
    public javax.swing.JButton btLanzar;
    public javax.swing.JButton btUnirse;
    public javax.swing.JButton btUnirsePartida;
    public javax.swing.JTextField idPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lConectado;
    public javax.swing.JLabel lDado1;
    public javax.swing.JLabel lDado2;
    private javax.swing.JLabel lIPContra;
    public javax.swing.JLabel lIPContra1;
    public javax.swing.JLabel lInstruccion;
    public javax.swing.JLabel lNumTablero;
    public javax.swing.JLabel lTurno;
    public javax.swing.JLabel lVidas;
    public javax.swing.JPanel pnlCrearUnirse;
    public javax.swing.JPanel pnlIServer;
    private javax.swing.JPanel pnlJugador;
    public javax.swing.JPanel pnlTablero;
    public javax.swing.JPanel pnlUnirse;
    // End of variables declaration//GEN-END:variables
}


